name: Build and Test

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          report_individual_runs: true
          junit_files: "**/build/test-results/**/*.xml"
