name: Unit Test Results
on:
  workflow_run:
    workflows: [Build and Test]
    types:
      - completed
jobs:
  unit-test-results:
    name: Unit Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    steps:
      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir -p artifacts && cd artifacts
          
          artifacts_url=${{ github.event.workflow_run.artifacts_url }}
          
          gh api "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
          do
            IFS=$'\t' read name url <<< "$artifact"
            gh api $url > "$name.zip"
            unzip -d "$name" "$name.zip"
          done
      - name: Display structure of downloaded files
        run: ls -ali artifacts/scavenger-agent-java
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          report_individual_runs: true
          check_name: "Scavenger Test Results"
          junit_files: "artifacts/**/build/test-results/**/*.xml"
